<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
    <AssemblyName>usbscope</AssemblyName>
    <RootNamespace>UsbScope.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsbScope.Core\UsbScope.Core.csproj" />
    <ProjectReference Include="..\UsbScope.Providers.Windows\UsbScope.Providers.Windows.csproj" />
  </ItemGroup>

</Project>
